# Generated by Django 4.2.25 on 2025-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_b24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlink',
            name='currency_cached',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='productlink',
            name='description_cached',
            field=models.TextField(blank=True),
        ),
    ]
